### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cngeru** [dilidili/react-drawing-board#4]
Can there be a feature where one adds a custom toolbar or customize the current one ?
Can one trasmit the events e.g using socket.io ?
**BUGS :**
The rectangular shape is missing 
Pressing Backspace while typing deletes the image

**Comment by dilidili** [comment]
Q: `Can there be a feature where one adds a custom toolbar or customize the current one ?`
A: I do not understand what is the specific customization you mean. e.g. text label and icon props configure?

Q: `Can one transmit the events e.g using socket.io ?`
A: You can receive newOperation on ```onChange``` called  and emit operations through socket.io, but the function should not be a part of this ```view lib```.

**BUGS:**

Q: `The rectangular shape is missing`
A: Can you provide a reproducible demo or screenshots help me location problem.

Q: `Pressing Backspace while typing deletes the image`
A: This problem maybe caused by pressing Backspace when some shape is selecting. Blur and preventing keyboard control will solve this problem?

**Comment by cngeru** [comment]
Can you add the features in this project [link to netless](https://github.com/netless-io/flat-web). The have limited the project for their services only.
